name: 'Deploy WordPress plugin'
description: 'Deploy WordPress plugin into SVN repository on WordPress.org powered by maintainable Python tested by pytest'
inputs: 
  expect-deploy-version-for-test:
    description: 'Expect deploy version only for test mode for CI'
    default: ''
  deploy-version-for-test:
    description: 'Deploy version only for test mode for CI'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    EXPECT_DEPLOY_VERSION_FOR_TEST: ${{ inputs.expect-deploy-version-for-test }}
    DEPLOY_VERSION_FOR_TEST: ${{ inputs.deploy-version-for-test }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
