name: 'Deploy WordPress plugin'
description: 'Deploy WordPress plugin into SVN repository on WordPress.org powered by maintainable Python tested by pytest'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
