name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.runs-on }}
    services:
      svn:
        image: futureys/svn-repository
        env:
          USER_1_NAME: svn_user_name
          USER_1_PASS: p@ssW0rd
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
        with:
          path: ./.github/actions/deploy

      - name: Checkout project
        uses: actions/checkout@v2
        repository: yukihiko-shinoda/staticpress
        ref: '0.4.1'
      - name: Back up environment variable
        run: echo ::set-env name=BACKUP_GITHUB_REF::$(echo "${GITHUB_REF}")
      - name: Overwrite deploy version
        run: echo ::set-env name=GITHUB_REF::$(echo refs/tags/0.4.1)
      - name: Deploy
        uses: ./.github/actions/deploy/
        env:
          SVN_REPOSITORY_URL: svn://svn/project-in-svn
          SVN_USER_NAME: svn_user_name
          SVN_USER_PASSWORD: p@ssW0rd
      - name: Restore environment variable
        run: echo ::set-env name=GITHUB_REF::$(echo "${BACKUP_GITHUB_REF}")

      - name: Checkout project
        uses: actions/checkout@v2
        repository: yukihiko-shinoda/staticpress
        ref: '0.4.2'
      - name: Back up environment variable
        run: echo ::set-env name=BACKUP_GITHUB_REF::$(echo "${GITHUB_REF}")
      - name: Overwrite deploy version
        run: echo ::set-env name=GITHUB_REF::$(echo refs/tags/0.4.2)
      - name: Deploy
        uses: ./.github/actions/deploy/
        env:
          SVN_REPOSITORY_URL: svn://svn/project-in-svn
          SVN_USER_NAME: svn_user_name
          SVN_USER_PASSWORD: p@ssW0rd
      - name: Restore environment variable
        run: echo ::set-env name=GITHUB_REF::$(echo "${BACKUP_GITHUB_REF}")

      - name: Checkout project
        uses: actions/checkout@v2
        repository: yukihiko-shinoda/staticpress
        ref: '0.4.5'
      - name: Back up environment variable
        run: echo ::set-env name=BACKUP_GITHUB_REF::$(echo "${GITHUB_REF}")
      - name: Overwrite deploy version
        run: echo ::set-env name=GITHUB_REF::$(echo refs/tags/0.4.5)
      - name: Deploy
        uses: ./.github/actions/deploy/
        env:
          SVN_REPOSITORY_URL: svn://svn/project-in-svn
          SVN_USER_NAME: svn_user_name
          SVN_USER_PASSWORD: p@ssW0rd
      - name: Restore environment variable
        run: echo ::set-env name=GITHUB_REF::$(echo "${BACKUP_GITHUB_REF}")
